name = Live
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = live-layout

; Regions
regions[top_header]     = Top Header
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[above_content]  = Above Content
regions[sidebar_first]  = First sidebar
regions[content]        = Content
regions[sidebar_second] = Second sidebar
regions[under_content]  = Under Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/simple/simple.layout.css
