name = eWingChun Frontpage
description = a layout for ewingchun.com frontpage
preview = preview.png
template = ewingchun-frontpage-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[banner]        = Banner
regions[content]        = Content
regions[content_columns]        = Content Columns
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/ewingchun/ewingchun.layout.css
stylesheets[all][] = css/layouts/ewingchun-frontpage/ewingchun-frontpage.layout.css

; Scripts
scripts[] = layouts/ewingchun/assets/ewingchun.js
