<?php

    function wc_user_preprocess_user_profile (&$variables) {
    //dpm($variables);
}

function wc_user_preprocess_user_picture(&$variables) {
    //dpm($variables);
}

function wc_user_user_view($account) {
  $account->content['join_date'] = array(
    '#theme' => 'field',
    '#weight' => '2',
    '#title' => t('Joined'),
    '#markup' => format_date($account->created, 'short'),
  );
  //dpm($account);
}