name = Sifu
description = a layout for ewingchun.com
preview = preview.png
template = sifu-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/ewingchun/ewingchun.layout.css
stylesheets[all][] = css/layouts/ewingchun/_ewingchun.css

; Scripts
scripts[] = layouts/ewingchun/assets/ewingchun.js
